name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with: 
          host: plantsforgrandma.de
          username: ${{ secrets.HOSTING_DE__USERNAME }}
          password: ${{ secrets.HOSTING_DE__PASSWORD }}
          port: ${{ secrets.HOSTING_DE__PORT }}
          script: |
            cd /home/webbhfjsr/html/plantsforgrandma.de && git pull origin main
